name: Get Changed Files
description: Get the files changed in a pull request or push.
author: Jitterbit, Inc.
branding:
  icon: file
  color: purple
runs:
  using: node12
  main: dist/index.js
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}
  format:
    description: >
      Format of the steps output context.
      Can be 'space-delimited', 'csv', or 'json'.
    required: true
    default: space-delimited
outputs:
  all:
    description: >
      Array of all changed files.
  added:
    description: >
      Array of added files.
  modified:
    description: >
      Array of modified files.
  deleted:
    description: >
      Array of deleted files.
  added_modified:
    description: >
      Array of all added and modified files.
