name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn

      - name: Clean, build, format, lint, package, and test
        run: |
          yarn all

      - name: Check if packaged properly
        run: |
          # If there are any unstaged or untracked files in 'dist/', then the action wasn't packaged properly
          if git diff --name-only | grep '^dist/' || git ls-files --other --exclude-standard | grep '^dist/'; then
            echo "You didn't package the action properly before pushing to remote." \
            echo "Always run 'yarn all' before staging a commit."
            echo "Below are the modified files in 'dist/' after running 'yarn && rm -rf dist/ && yarn all':"
            git diff --name-only | grep '^dist/'
            git ls-files --other --exclude-standard | grep '^dist/'
            exit 1
          fi

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: files
        name: Run the action
        uses: ./
        with:
          disk: true

      - name: Print steps context output
        run: |
          echo 'steps.files.outputs.all=${{ steps.files.outputs.all }}'
          echo 'steps.files.outputs.added=${{ steps.files.outputs.added }}'
          echo 'steps.files.outputs.deleted=${{ steps.files.outputs.deleted }}'
          echo 'steps.files.outputs.modified=${{ steps.files.outputs.modified }}'
          echo 'steps.files.outputs.added_modified=${{ steps.files.outputs.added_modified }}'

      - name: Print disk output
        run: |
          echo "./files/all.json=$(cat ./files/all.json)"
          echo "./files/added.json=$(cat ./files/added.json)"
          echo "./files/deleted.json=$(cat ./files/deleted.json)"
          echo "./files/modified.json=$(cat ./files/modified.json)"
          echo "./files/added_modified.json=$(cat ./files/added_modified.json)"
